"""Benchmark repeated NUFFT evaluations for a short 3.5PN chirp signal."""

import argparse
import sys
import time
from pathlib import Path

import numpy as np


PAPER_PLOTS_DIR = Path(__file__).resolve().parents[1]
if str(PAPER_PLOTS_DIR) not in sys.path:
    sys.path.insert(0, str(PAPER_PLOTS_DIR))

from resampler import Resampler, clear_plan_cache
from signal_generators import beta_0pn, make_35pn_track, tau_0pn


MC_MSUN = 1e-2
F0_HZ = 40.0
T_OBS = 30.0
F_SAMP_HZ = 256.0
THREADS = 4
REPEATS = 5
MIN_SECONDS = 1.0
EPS = 1e-3


def build_signal(mchirp_msun, f0_hz, duration, sampling_frequency):
    """Return a complex 3.5PN signal with a matching 0PN resampled time axis."""

    n_samples = int(round(duration * sampling_frequency))
    actual_duration = n_samples / sampling_frequency
    if not np.isclose(actual_duration, duration):
        raise ValueError(
            "duration * sampling_frequency must be an integer number of samples; "
            f"got {duration} * {sampling_frequency} = {duration * sampling_frequency}."
        )

    t = np.arange(n_samples, dtype=np.float64) / sampling_frequency
    beta = beta_0pn(f0_hz, mchirp_msun)
    track = make_35pn_track(
        t,
        f0_hz=f0_hz,
        f_stop_hz=0.5 * sampling_frequency,
        mchirp_msun=mchirp_msun,
    )
    tau = np.asarray(tau_0pn(t, beta), dtype=np.float64)
    signal = np.asarray(track.signal, dtype=np.complex128)
    return t, signal, tau, beta


def time_nufft_batch(resampler, iterations):
    start = time.perf_counter()
    for _ in range(iterations):
        resampler.nufft()
    return time.perf_counter() - start


def choose_iterations(resampler, min_seconds):
    iterations = 1
    elapsed = time_nufft_batch(resampler, iterations)
    while elapsed < min_seconds:
        scale = max(2, int(np.ceil(min_seconds / max(elapsed, 1e-12))))
        iterations *= scale
        elapsed = time_nufft_batch(resampler, iterations)
    return iterations


def run_benchmark(
    mchirp_msun=MC_MSUN,
    f0_hz=F0_HZ,
    duration=T_OBS,
    sampling_frequency=F_SAMP_HZ,
    threads=THREADS,
    eps=EPS,
    precision="double",
    upsampfac=1.25,
    repeats=REPEATS,
    min_seconds=MIN_SECONDS,
    iterations=None,
):
    t, signal, tau, beta = build_signal(
        mchirp_msun=mchirp_msun,
        f0_hz=f0_hz,
        duration=duration,
        sampling_frequency=sampling_frequency,
    )

    clear_plan_cache()
    resampler = Resampler(
        nthreads=threads,
        eps=eps,
        precision=precision,
        upsampfac=upsampfac,
    )
    resampler.timeseries = signal
    resampler.resampled_time = tau

    # Warm up FINUFFT planning and cache allocation outside the timing loop.
    resampler.nufft()

    if iterations is None:
        iterations = choose_iterations(resampler, min_seconds)

    elapsed_times = np.empty(repeats, dtype=float)
    for idx in range(repeats):
        elapsed_times[idx] = time_nufft_batch(resampler, iterations)

    evals_per_second = iterations / elapsed_times
    median_elapsed = float(np.median(elapsed_times))
    median_rate = float(np.median(evals_per_second))

    return {
        "mchirp_msun": mchirp_msun,
        "f0_hz": f0_hz,
        "duration": duration,
        "sampling_frequency": sampling_frequency,
        "samples": signal.size,
        "tau_span": float(tau[-1] - tau[0]),
        "beta": beta,
        "threads": threads,
        "eps": eps,
        "precision": precision,
        "upsampfac": upsampfac,
        "repeats": repeats,
        "iterations": iterations,
        "elapsed_times": elapsed_times,
        "evals_per_second": evals_per_second,
        "median_elapsed": median_elapsed,
        "median_rate": median_rate,
        "median_samples_per_second": signal.size * median_rate,
        "milliseconds_per_eval": 1e3 / median_rate,
        "peak_frequency_hz": float(resampler.freq_in_hz[np.argmax(resampler.power)]),
    }


def parse_args():
    parser = argparse.ArgumentParser(
        description=(
            "Benchmark full Resampler.nufft() evaluations on a 3.5PN signal "
            "generated by signal_generators.py and resampled with the 0PN tau."
        )
    )
    parser.add_argument("--mchirp", type=float, default=MC_MSUN)
    parser.add_argument("--f0", type=float, default=F0_HZ)
    parser.add_argument("--duration", type=float, default=T_OBS)
    parser.add_argument("--fsamp", type=float, default=F_SAMP_HZ)
    parser.add_argument("--threads", type=int, default=THREADS)
    parser.add_argument("--eps", type=float, default=EPS)
    parser.add_argument("--precision", choices=("double", "single"), default="double")
    parser.add_argument("--upsampfac", type=float, default=1.25)
    parser.add_argument("--repeats", type=int, default=REPEATS)
    parser.add_argument(
        "--min-seconds",
        type=float,
        default=MIN_SECONDS,
        help="Minimum timing duration used to auto-select iterations.",
    )
    parser.add_argument(
        "--iterations",
        type=int,
        default=None,
        help="NUFFT evaluations per repeat. Defaults to an auto-selected value.",
    )
    return parser.parse_args()


def main():
    args = parse_args()
    result = run_benchmark(
        mchirp_msun=args.mchirp,
        f0_hz=args.f0,
        duration=args.duration,
        sampling_frequency=args.fsamp,
        threads=args.threads,
        eps=args.eps,
        precision=args.precision,
        upsampfac=args.upsampfac,
        repeats=args.repeats,
        min_seconds=args.min_seconds,
        iterations=args.iterations,
    )

    print("NUFFT benchmark")
    print(f"  Mc:                  {result['mchirp_msun']:.6g} Msun")
    print(f"  f0:                  {result['f0_hz']:.6g} Hz")
    print(f"  duration:            {result['duration']:.6g} s")
    print(f"  sampling frequency:  {result['sampling_frequency']:.6g} Hz")
    print(f"  samples/modes:       {result['samples']}")
    print(f"  tau span:            {result['tau_span']:.9g} s")
    print(f"  beta:                {result['beta']:.9g}")
    print(f"  peak frequency:      {result['peak_frequency_hz']:.9g} Hz")
    print(f"  threads:             {result['threads']}")
    print(f"  eps:                 {result['eps']:.3g}")
    print(f"  precision:           {result['precision']}")
    print(f"  upsampfac:           {result['upsampfac']:.3g}")
    print(f"  repeats:             {result['repeats']}")
    print(f"  iterations/repeat:   {result['iterations']}")
    print(
        "  elapsed/repeat:      "
        + ", ".join(f"{value:.6f}s" for value in result["elapsed_times"])
    )
    print(f"  median time/eval:    {result['milliseconds_per_eval']:.6g} ms")
    print(f"  median NUFFTs/s:     {result['median_rate']:.6g}")
    print(f"  median samples/s:    {result['median_samples_per_second']:.6g}")


if __name__ == "__main__":
    main()
